### ISSUE TITLE
OverallFeedback receives type never

### ISSUE THREAD

**Issue by henriettemoe** [boyum/h5p-types#1001]
When using `InferParamsFromSemantics` to get the correct type for the params, overallFeedback (similar to what's used in h5p-blanks and h5p-drag-text) receives type never. Is there a support for this that could be added to h5p-types or does the semantics for overallFeedback need to change?

**Comment by boyum** [comment]
Interesting! Do you have a link to a repo where this is used?

**Comment by boyum** [comment]
This should be fixed in 5.2.0. Please verify.
