### ISSUE TITLE
'tags' does not exist in type 'H5PFieldText'

### ISSUE THREAD

**Issue by henriettemoe** [boyum/h5p-types#1052]
When using tags on a text field in semantics.json like this:

```
{
  "label": "Text",
  "name": "text",
  "type": "text",
  "widget": "html",
  "optional": true,
  "tags": [
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "br",
    "strong",
    "em",
    "a"
  ]
}
```

and having it typed as `H5PFieldText` in a semantics.ts file, it gives an Error: 

> Object literal may only specify known properties, and 'tags' does not exist in type 'H5PFieldText'.

Happens in version 5.0.0 and later.

**Comment by boyum** [comment]
This bug was introduced in https://github.com/boyum/h5p-types/releases/tag/h5p-types-5.1.0
